export const LOAD_ASSETS_SUCCESS='LOAD_ASSETS_SUCCES';
export const CREATE_ASSET_SUCCESS='CREATE_ASSET_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS='LOAD_CATEGORIES_SUCCESS';
export const UPDATE_ASSET_SUCCESS='UPDATE_ASSET_SUCCESS';
export const DELETE_ASSET_SUCCESS='DELETE_ASSET_SUCCESS';